import * as React from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Check } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth/AuthProvider";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_app/leagues/new")({
  head: () => ({ meta: [{ title: "New league · Bisque" }] }),
  component: NewLeaguePage,
});

type Discipline = "gc" | "ac";

function NewLeaguePage() {
  const navigate = useNavigate();
  const { user } = useAuth();

  const [name, setName] = React.useState("");
  const [discipline, setDiscipline] = React.useState<Discipline>("gc");
  const [handicap, setHandicap] = React.useState<string>("");
  const [profileHandicap, setProfileHandicap] = React.useState<number | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [touched, setTouched] = React.useState<{ name: boolean; handicap: boolean }>({
    name: false,
    handicap: false,
  });

  // Load current profile handicap to prefill the input.
  React.useEffect(() => {
    if (!user) return;
    let cancelled = false;
    void (async () => {
      const { data, error: pErr } = await supabase
        .from("profiles")
        .select("gc_handicap")
        .eq("id", user.id)
        .maybeSingle();
      if (cancelled) return;
      if (pErr) {
        // Non-blocking — keep field empty for the user to fill in.
        return;
      }
      if (data && typeof data.gc_handicap === "number") {
        setProfileHandicap(data.gc_handicap);
        setHandicap(String(data.gc_handicap));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [user]);

  const trimmedName = name.trim();
  const nameLength = trimmedName.length;
  const nameValid = nameLength > 0 && nameLength <= 50;

  const handicapNum = Number(handicap);
  const handicapValid =
    handicap !== "" &&
    Number.isInteger(handicapNum) &&
    handicapNum >= -3 &&
    handicapNum <= 24;

  const formValid = nameValid && handicapValid;

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setTouched({ name: true, handicap: true });
    if (!formValid || !user) return;
    setBusy(true);
    setError(null);

    try {
      // 1. Insert league. join_code is auto-generated by DB default.
      const { data: league, error: lErr } = await supabase
        .from("leagues")
        .insert({
          name: trimmedName,
          owner_id: user.id,
          format: "singles",
          handicap_enabled: true,
        })
        .select("id")
        .single();
      if (lErr) throw lErr;
      if (!league) throw new Error("League could not be created.");

      // 2. Insert admin membership (no trigger attached). Swallow duplicate
      //    errors in case a trigger gets added later.
      const { error: mErr } = await supabase.from("league_members").insert({
        league_id: league.id,
        user_id: user.id,
        role: "admin",
      });
      if (mErr && mErr.code !== "23505") {
        throw mErr;
      }

      // 3. Update profile handicap if it changed. Non-blocking.
      if (profileHandicap === null || handicapNum !== profileHandicap) {
        const { error: upErr } = await supabase
          .from("profiles")
          .update({ gc_handicap: handicapNum })
          .eq("id", user.id);
        if (upErr) {
          console.warn("Failed to update profile handicap:", upErr.message);
        }
      }

      toast.success("League created");
      void navigate({
        to: "/leagues/$leagueId",
        params: { leagueId: league.id },
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Could not create league.";
      setError(msg);
      toast.error(msg);
      setBusy(false);
    }
  }

  return (
    <div className="mx-auto w-full max-w-md px-5 pb-12 pt-6 md:pt-12">
      <Link
        to="/leagues"
        className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="size-4" aria-hidden /> Back to Leagues
      </Link>

      <div className="mt-8">
        <h1 className="font-display text-3xl font-medium tracking-tight text-foreground md:text-4xl">
          Create a league.
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Name it, pick your discipline, and set your handicap. You can invite players right
          after.
        </p>
      </div>

      <form onSubmit={onSubmit} className="mt-8 space-y-5">
        {/* League name */}
        <div className="space-y-2">
          <Label htmlFor="league-name">League name</Label>
          <Input
            id="league-name"
            type="text"
            autoComplete="off"
            maxLength={50}
            placeholder="e.g., Sunday Sixes"
            value={name}
            onChange={(e) => {
              setName(e.target.value);
              if (error) setError(null);
            }}
            onBlur={() => setTouched((t) => ({ ...t, name: true }))}
            className="tap"
          />
          <div className="flex items-center justify-between">
            {touched.name && !nameValid ? (
              <p className="text-xs font-medium text-destructive">
                League name is required
              </p>
            ) : (
              <span />
            )}
            <span className="text-xs text-muted-foreground tabular-nums">
              {nameLength}/50
            </span>
          </div>
        </div>

        {/* Discipline */}
        <div className="space-y-2">
          <Label>Croquet discipline</Label>
          <div className="grid gap-2">
            <button
              type="button"
              onClick={() => setDiscipline("gc")}
              aria-pressed={discipline === "gc"}
              className={cn(
                "tap flex items-center justify-between rounded-md border bg-transparent px-3 py-3 text-left text-sm shadow-sm transition-colors",
                discipline === "gc"
                  ? "border-primary text-foreground"
                  : "border-input text-foreground hover:bg-accent",
              )}
            >
              <span className="font-medium">Golf Croquet (GC)</span>
              {discipline === "gc" && (
                <span className="flex size-5 items-center justify-center rounded-full bg-primary text-primary-foreground">
                  <Check className="size-3.5" aria-hidden />
                </span>
              )}
            </button>
            <button
              type="button"
              disabled
              aria-disabled
              className="tap flex cursor-not-allowed items-center justify-between rounded-md border border-input bg-transparent px-3 py-3 text-left text-sm opacity-60 shadow-sm"
            >
              <span className="font-medium">Association Croquet (AC)</span>
              <span className="text-xs text-muted-foreground">Coming soon</span>
            </button>
          </div>
        </div>

        {/* Handicap */}
        <div className="space-y-2">
          <Label htmlFor="gc-handicap">My GC handicap</Label>
          <Input
            id="gc-handicap"
            type="number"
            inputMode="numeric"
            min={-3}
            max={24}
            step={1}
            placeholder="e.g., 12"
            value={handicap}
            onChange={(e) => {
              setHandicap(e.target.value);
              if (error) setError(null);
            }}
            onBlur={() => setTouched((t) => ({ ...t, handicap: true }))}
            className="tap tabular-nums"
          />
          {touched.handicap && !handicapValid ? (
            <p className="text-xs font-medium text-destructive">
              {handicap === ""
                ? "Handicap is required"
                : "Handicap must be a whole number between −3 and 24"}
            </p>
          ) : (
            <p className="text-xs text-muted-foreground">
              Range: −3 (best) to 24 (beginner)
            </p>
          )}
        </div>

        {error && (
          <p className="text-xs font-medium text-destructive" role="alert">
            {error}
          </p>
        )}

        <Button
          type="submit"
          disabled={!formValid || busy}
          className="tap w-full text-base"
        >
          {busy ? "Creating…" : "Create league"}
        </Button>
      </form>
    </div>
  );
}
