/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLeaguesRouteImport } from './routes/_app.leagues'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app.settings.privacy'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppLeaguesNewRouteImport } from './routes/_app.leagues.new'
import { Route as AppLeaguesJoinRouteImport } from './routes/_app.leagues.join'
import { Route as AppLeaguesLeagueIdRouteImport } from './routes/_app.leagues.$leagueId'
import { Route as AppLeaguesLeagueIdMatchesNewRouteImport } from './routes/_app.leagues.$leagueId.matches.new'
import { Route as AppLeaguesLeagueIdMatchesMatchIdRouteImport } from './routes/_app.leagues.$leagueId.matches.$matchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesRoute = AppLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLeaguesNewRoute = AppLeaguesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLeaguesRoute,
} as any)
const AppLeaguesJoinRoute = AppLeaguesJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppLeaguesRoute,
} as any)
const AppLeaguesLeagueIdRoute = AppLeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => AppLeaguesRoute,
} as any)
const AppLeaguesLeagueIdMatchesNewRoute =
  AppLeaguesLeagueIdMatchesNewRouteImport.update({
    id: '/matches/new',
    path: '/matches/new',
    getParentRoute: () => AppLeaguesLeagueIdRoute,
  } as any)
const AppLeaguesLeagueIdMatchesMatchIdRoute =
  AppLeaguesLeagueIdMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => AppLeaguesLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/leagues': typeof AppLeaguesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/leagues/$leagueId': typeof AppLeaguesLeagueIdRouteWithChildren
  '/leagues/join': typeof AppLeaguesJoinRoute
  '/leagues/new': typeof AppLeaguesNewRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/leagues/$leagueId/matches/$matchId': typeof AppLeaguesLeagueIdMatchesMatchIdRoute
  '/leagues/$leagueId/matches/new': typeof AppLeaguesLeagueIdMatchesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/leagues': typeof AppLeaguesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/leagues/$leagueId': typeof AppLeaguesLeagueIdRouteWithChildren
  '/leagues/join': typeof AppLeaguesJoinRoute
  '/leagues/new': typeof AppLeaguesNewRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/leagues/$leagueId/matches/$matchId': typeof AppLeaguesLeagueIdMatchesMatchIdRoute
  '/leagues/$leagueId/matches/new': typeof AppLeaguesLeagueIdMatchesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/leagues': typeof AppLeaguesRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/leagues/$leagueId': typeof AppLeaguesLeagueIdRouteWithChildren
  '/_app/leagues/join': typeof AppLeaguesJoinRoute
  '/_app/leagues/new': typeof AppLeaguesNewRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/leagues/$leagueId/matches/$matchId': typeof AppLeaguesLeagueIdMatchesMatchIdRoute
  '/_app/leagues/$leagueId/matches/new': typeof AppLeaguesLeagueIdMatchesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/home'
    | '/leagues'
    | '/profile'
    | '/settings'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/leagues/new'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/leagues/$leagueId/matches/$matchId'
    | '/leagues/$leagueId/matches/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/home'
    | '/leagues'
    | '/profile'
    | '/settings'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/leagues/new'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/leagues/$leagueId/matches/$matchId'
    | '/leagues/$leagueId/matches/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/home'
    | '/_app/leagues'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/leagues/$leagueId'
    | '/_app/leagues/join'
    | '/_app/leagues/new'
    | '/_app/settings/appearance'
    | '/_app/settings/notifications'
    | '/_app/settings/privacy'
    | '/_app/leagues/$leagueId/matches/$matchId'
    | '/_app/leagues/$leagueId/matches/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leagues': {
      id: '/_app/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AppLeaguesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/leagues/new': {
      id: '/_app/leagues/new'
      path: '/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof AppLeaguesNewRouteImport
      parentRoute: typeof AppLeaguesRoute
    }
    '/_app/leagues/join': {
      id: '/_app/leagues/join'
      path: '/join'
      fullPath: '/leagues/join'
      preLoaderRoute: typeof AppLeaguesJoinRouteImport
      parentRoute: typeof AppLeaguesRoute
    }
    '/_app/leagues/$leagueId': {
      id: '/_app/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AppLeaguesLeagueIdRouteImport
      parentRoute: typeof AppLeaguesRoute
    }
    '/_app/leagues/$leagueId/matches/new': {
      id: '/_app/leagues/$leagueId/matches/new'
      path: '/matches/new'
      fullPath: '/leagues/$leagueId/matches/new'
      preLoaderRoute: typeof AppLeaguesLeagueIdMatchesNewRouteImport
      parentRoute: typeof AppLeaguesLeagueIdRoute
    }
    '/_app/leagues/$leagueId/matches/$matchId': {
      id: '/_app/leagues/$leagueId/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/leagues/$leagueId/matches/$matchId'
      preLoaderRoute: typeof AppLeaguesLeagueIdMatchesMatchIdRouteImport
      parentRoute: typeof AppLeaguesLeagueIdRoute
    }
  }
}

interface AppLeaguesLeagueIdRouteChildren {
  AppLeaguesLeagueIdMatchesMatchIdRoute: typeof AppLeaguesLeagueIdMatchesMatchIdRoute
  AppLeaguesLeagueIdMatchesNewRoute: typeof AppLeaguesLeagueIdMatchesNewRoute
}

const AppLeaguesLeagueIdRouteChildren: AppLeaguesLeagueIdRouteChildren = {
  AppLeaguesLeagueIdMatchesMatchIdRoute: AppLeaguesLeagueIdMatchesMatchIdRoute,
  AppLeaguesLeagueIdMatchesNewRoute: AppLeaguesLeagueIdMatchesNewRoute,
}

const AppLeaguesLeagueIdRouteWithChildren =
  AppLeaguesLeagueIdRoute._addFileChildren(AppLeaguesLeagueIdRouteChildren)

interface AppLeaguesRouteChildren {
  AppLeaguesLeagueIdRoute: typeof AppLeaguesLeagueIdRouteWithChildren
  AppLeaguesJoinRoute: typeof AppLeaguesJoinRoute
  AppLeaguesNewRoute: typeof AppLeaguesNewRoute
}

const AppLeaguesRouteChildren: AppLeaguesRouteChildren = {
  AppLeaguesLeagueIdRoute: AppLeaguesLeagueIdRouteWithChildren,
  AppLeaguesJoinRoute: AppLeaguesJoinRoute,
  AppLeaguesNewRoute: AppLeaguesNewRoute,
}

const AppLeaguesRouteWithChildren = AppLeaguesRoute._addFileChildren(
  AppLeaguesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppLeaguesRoute: typeof AppLeaguesRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppLeaguesRoute: AppLeaguesRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
